### ISSUE TITLE
Enumerating all types in all assemblies breaks dynamically managed references

### ISSUE THREAD

**Issue by int19h** [Aragas/Bannerlord.MBOptionScreen#105]
I'm the author of https://github.com/int19h/Bannerlord.CSharp.Scripting, and I've had some user reports regarding its incompatibilities with MCM. I have investigated it, and I think this is something that needs to be fixed on MCM side.

The MCM code in question is this:
https://github.com/Aragas/Bannerlord.MBOptionScreen/blob/0a4e70190db9f89f63eda2575781b27fe412e94b/src/MCM/Implementation/Settings/Containers/PerSave/MCMPerSaveSettingsContainer.cs#L54-L59
And specifically, the part that calls `GetTypes()` on every loaded assembly. It might sound weird - certainly was weird to me! - but, apparently, this is not a safe operation on just any random assembly. 

The reason is that some assemblies have references to other assemblies that might not always be there at runtime, and rely on .NET rules for when types get loaded (i.e. on first reference, not on assembly load) to ensure that such types are not loaded when the reference isn't there. The specific case that me and my users are hitting is Roslyn, which uses `System.Runtime.Loader` on .NET Core/5, and `Assembly.Load` etc otherwise. They implement this by having different classes for each, and dynamically instantiating one or the other depending on the platform:

https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/Scripting/Core/Hosting/AssemblyLoader/AssemblyLoaderImpl.cs#L24-L41

That is, `CoreAssemblyLoaderImpl` is the class that only works on Core/5, and will cause an exception otherwise - but in normal Roslyn operation, it just never gets loaded when running on desktop CLR, and thus everything is fine.

But when MCM calls `GetTypes()` on `Microsoft.CodeAnalysis.Scripting` assembly, it forces all types in the assembly to be loaded regardless - and that load then causes a missing assembly exception for `System.Runtime.Loader`, which is uncaught, and thus crashes the game.

I believe the technique used by Roslyn is valid - CLR delayed loading for types is well-specified for this reason, among others. So the fix should be on the `GetTypes()` side of things. Specifically, it cannot assume that `GetTypes()` is exception-free (indeed, it is is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.gettypes?view=netframework-4.8#exceptions) to not be). The easiest fix would be for the loop to wrap `GetTypes()` in a try-catch for `ReflectionTypeLoadException`, and simply ignore any assembly that causes it.

**Comment by Aragas** [comment]
Hi!
Good point, I actually had some experience with the issue when I was working on the Harmony Extension library, we indeed catch the exception and return the valid types from the assembly.
https://github.com/BUTR/Harmony.Extensions/blob/master/src/Harmony.Extensions/AccessTools2.cs#L176
I'll switch to this implementation, it should fix the issue, if I understand everything correctly

**Comment by Aragas** [comment]
Can you check if v4.3.12 fixes the issue?

**Comment by int19h** [comment]
It does; thank you!
