### ISSUE TITLE
Exception when initializing MBOptionScreenSubModuleV2010

### ISSUE THREAD

**Issue by SaulHE** [Aragas/Bannerlord.MBOptionScreen#14]
Crash Report Image: https://imgur.com/mKPJfzl

This is a very rare crashing. 

Only one of my mod's user encounters this when using the launcher to start the game.

I remote access his computer. No matter I include MBOptionScreen.v2.0.10.dll in my module or as a reference from a standalone MCM.

This error happens.

His game and other mods are fine. But the initialization of MCM just keeps crashing for couldn't detect the 'id' parameter.

And what's your discord channel, please? I would like to join.

**Comment by Aragas** [comment]
https://discord.gg/8vKVnU

It's an interesting issue. Might be related to a broken implementation of MCM from some mod. Was there any conclusion to this bug? Did the beta fix anything?
