### ISSUE TITLE
Share per-campaign settings between campaigns

### ISSUE THREAD

**Issue by welles** [Aragas/Bannerlord.MBOptionScreen#142]
Hi there! As always, thanks for your great work!
Since I have switched my mod to per-campaign settings, my users have been asking for a way to share settings between campaigns because they keep having to reconfigure when starting a new one.
Could you add something like that?

My ideas would be:
- Add import/export buttons that save/load the current settings to/from a file
- Add a "favorites" system that is just a menu where you can save/load settings configurations, which are shared between campaigns

Cheers!

**Comment by Aragas** [comment]
PerCampaign settings are now shareable. I'll work on a feature to share the whole settings pack

**Comment by Aragas** [comment]
The ability to create settings packs and Import/Export them is done via v5.9.0

**Comment by Aragas** [comment]
The current implementation doesn't have a place for a "favorite" system, so unless a better redesign is provided, it won't be implemented for now
