### ISSUE TITLE
When is settings guaranteed to be loaded?

### ISSUE THREAD

**Issue by sgsdxzy** [Aragas/Bannerlord.MBOptionScreen#19]
It is stated in the wiki that "you should not use Settings.Instance in OnSubModuleLoad() as the setting might still not be loaded depending on mod loading order".
However, I need to harmony patch some Deserailize methods, for example TaleWorlds.Core.WeaponComponentData.Deserailize, before any xml is loaded. By my own observations, xmls are loaded when a save is loaded. So I suppose the patching has to be done before OnGameStart() to be safe.
So if it is not reliable to get settings in OnSubModuleLoad(), when is settings guaranteed to be loaded?

**Comment by SebLavK** [comment]
I use `OnBeforeInitialModuleScreenSetAsRoot`, which is after all the modules are loaded (and hence, MCM loads the settings) and right before the main menu is shown.

**Comment by sgsdxzy** [comment]
> I use `OnBeforeInitialModuleScreenSetAsRoot`, which is after all the modules are loaded (and hence, after MCM loads the settings) and right before the main menu is shown.

Thanks, I will give it a try.

**Comment by SebLavK** [comment]
I forgot to mention it not only triggers when you start the game, but also when you exit to the main menu, so you might want to control that.

**Comment by sgsdxzy** [comment]
Thanks, I managed to get it working.
