### ISSUE TITLE
Breaking Modlib mods

### ISSUE THREAD

**Issue by PoPoWanObi** [Aragas/Bannerlord.MBOptionScreen#2]
Feel free to read my mod's posts.
https://www.nexusmods.com/mountandblade2bannerlord/mods/118/?tab=posts&BH=0

**Comment by Aragas** [comment]
Noted. Will be fixing it

**Comment by Aragas** [comment]
1.0.7 (latest commit) should fix most issues with ModLib
* Group Names show
* Save/Load/Resetting settings work

One issue left. When resetting the settings, the interface is not updated. Will look into it later.

**Comment by PoPoWanObi** [comment]
Alright appreciate that; thank you.
