### ISSUE TITLE
Huge performance drop in MCM v3

### ISSUE THREAD

**Issue by sgsdxzy** [Aragas/Bannerlord.MBOptionScreen#23]
I tried to port my mod from MBOptionScreen v2.0.10 to MCM.Integrated v3.1.0, and the performance drops badly. Both are using attributes api v2.
I ran a performance profiler of CPU in Visual Studio comparing both versions:
MBOptionScreen is taking no more than 0.05% of CPU time;
MCM is using more than 30%. DefaultDropdown::ctor is using more than 20% alone (and there is only a single instance of DefaultDropdown is my settings class). GlobalSettings::get_instance is using 7%, and AttributeGlobalSettings::ctor is using 2.46%.
It looks like `AttributeGlobalSettings.Instance` is not working correctly, that everytime it is called it creates and returns a new instance, otherwise the ctors should only be called once and not eating so much CPU time.

**Comment by Aragas** [comment]
The reason why the constructor is called every time .Instance is called is because it need the Id property.
I could cache the instance so it won't be created every time.
The 'workaround' will be available in 3.1.2

**Comment by sgsdxzy** [comment]
I find that keeping a static reference to the instance can overcome this issue.
Instead of calling Settings.Instance every time, one could assign the instance to a static member once, and use that every time.
It is up to you whether the 'workaround' is really necessary, or just clarify Settings.Instance is expensive and one should keep his own reference to the instance.
