### ISSUE TITLE
Incompatible Saving

### ISSUE THREAD

**Issue by PoPoWanObi** [Aragas/Bannerlord.MBOptionScreen#3]
Hard to explain this one, but hopefully you'll understand.

With ModLib from Mipen everything works fine when not running alongside MBOptionScreen.

With MBOptionScreen it is saving as well, but ModLib mods aren't reading this save. So while you can make the save to enable something, it won't register with ModLib on the next startup of the game.

In order to get ModLib mods to save and read, you must do so prior to using a mod with MBOptionScreen.

Just some feedback I received. ~

**Comment by Aragas** [comment]
Noted. Will investige a workaround for that!

**Comment by Infinizhen** [comment]
Thanks, intercompatibility between these two would be awesome!

**Comment by Aragas** [comment]
Should be fixed with 1.1.9

**Comment by PoPoWanObi** [comment]
Thanks for your fine work. :)
