### ISSUE TITLE
Fluent API Question

### ISSUE THREAD

**Issue by mgemperl** [Aragas/Bannerlord.MBOptionScreen#30]
I'm having trouble figuring out how to use the Fluent API Default Settings Builder with MCMv3.14 Integrated and Bannerlord version e1.4.0.

I have this code in a singleton, which builds and registers some global settings:
```
private FluentGlobalSettings _settings;
float _testFloat = 0;

public void BuildSettings()
{
    var builder = new DefaultSettingsBuilder("Test_v1", "Test Mod")
        .SetFormat("json")
        .SetFolderName(SubModule.ModuleFolderName)
        .SetSubFolder("")
        .CreateGroup("Test Group", groupBuilder =>
            groupBuilder.AddFloatingInteger("Test Name", 0f, 20f,
                new ProxyRef<float>(() => _testFloat, (value) => _testFloat = value),
                floatBuilder => floatBuilder
                    .SetHintText("Test Hint")));

    _settings = builder.BuildAsGlobal();
    _settings.Register();
}
```

And I can't seem to get those test settings to appear in the MCM Mod Options menu no matter when I call my BuildSettings method in the lifecycle. I do see the option menus for the three MCM modules though, I just don't see mine.

When exactly should we be registering settings that are built with the Fluent API? The Wiki mentioned it should be after the player loads into a campaign, but it still doesn't seem to appear in the in-game MCM Mod Options menu when I attempt to register settings by calling my BuildSettings method from an MBSubModuleBase.OnGameLoaded override:
```
public override void OnGameLoaded(Game game, object initializerObject)
{
    base.OnGameLoaded(game, initializerObject);
    Settings.Instance.BuildSettings();
}
```

Am I doing something obviously wrong here, or am I just misunderstanding something?

**Comment by Aragas** [comment]
Global settings can be registered at any time!
Its the PerCharacter type that has this limitation

**Comment by Aragas** [comment]
I'll recheck a bit later if the Fluent API has some display issues

**Comment by Aragas** [comment]
Yea, there is an issue with the register method, will be fixed in 3.1.5!

**Comment by mgemperl** [comment]
Thanks for the quick responses! I'm glad to hear a fix is coming.

MCM has been a huge help, and I'm grateful for all the hard work you've been putting into it.

**Comment by mgemperl** [comment]
All right, I can confirm the settings are showing up in the mod options menu with MCMv3.1.5 Integrated.

I've run into a new problem, though. After editing the value in those test settings I initially posted, the json file saved to disc is one line long and contains only an empty object:

```
{}
```

I had a similar result saving as xml, just getting a single empty FluentGlobalSettings element.

```
<?xml version="1.0" encoding="utf-8"?>
<FluentGlobalSettings />
```

Could this be another bug, or could this be caused by a configuration error on my part?

**Comment by Aragas** [comment]
Probably the MCM fault. I'll check the issue and do a quick 3.1.6 update then if it's a bug

**Comment by Aragas** [comment]
Yea, there is some missing logic that I need to replace with fluent api, somehow missed that.
The fix won't be in 3.1.6, instead it will be in 3.1.7. I discovered a major bug, so it will be fixed first, then the fluent api. Still should be today tho

**Comment by mgemperl** [comment]
Thanks, I appreciate it.

**Comment by Aragas** [comment]
The issue was harder than expected, needed to refactor the serialization and I'm still not satisfied, but now it should work

**Comment by mgemperl** [comment]
Thanks, the config file is being saved correctly now, but it isn't being loaded for some reason.

I tried cloning this repo and debugging a bit, and I'm noticing that the FluentGlobalSettings.Register method simply adds the fluent settings to the FluentGlobalSettingsContainer.LoadedSettings dictionary without attempting to load a config file from disc (if I'm understanding it correctly, anyway).

I think it would fit your architecture best to have the FluentGlobalSettingsContainer be responsible for the fluent settings registration process, since the container has access to the BaseSettingsContainer file IO functionality that is used to load the attribute settings config files. Although, I can't really think of a good way to expose a registration method in the DefaultSettingsProvider's FluentGlobalSettingsContainer to other mod creators...

Or perhaps the DefaultSettingsBuilder could check for and load a config file if one exists when the settings are built. This would probably be easier, but I'm not sure whether config file loading should be part the builder's responsibilities.

I don't have much software development experience though, so I'm sure there are better solutions.

**Comment by mgemperl** [comment]
I suppose you could also just expose the FluentGlobalSettingsContainer to the FluentGlobalSettings class itself. Then the FluentGlobalSettings.Register method could have access to the file IO functionality from BaseSettingsContainer. 

Would it be possible to store settings containers in the AppDomain rather than dictionaries?

**Comment by Aragas** [comment]
Thanks for helping with the issue!
Yep, I was careless and didn't notice that he IO was not even used.

The approach to fix this will be most likely a hybrid of ModLib's implementation. Reload the settings from the appdomain storage and register them if they weren't before. I've already implemented it, still need to test if everything works

The reason for using a dictionary instead of just scattering them in the appdomain storage was to make it more easy to switch to something better. I'm not a big fan of using AppDomain for such functionality, but it was the first what came in mind.

**Comment by mgemperl** [comment]
Thanks, that makes sense. And I was getting curious why AppDomain's storage was used only for the Fluent API. I agree it works fine as a temporary solution, and I suppose a better idea will come along eventually.

I think my last question may have been unclear, though. I meant to ask whether it's a good idea to store the FluentGlobalSettingsContainer object in the AppDomain, and then in the FluentGlobalSettings.Register method, the FluentGlobalSettings object could add itself to the FluentGlobalSettingsContainer.LoadedSettings dictionary and invoke some new method in FluentGlobalSettingsContainer that loads the file from disc. I don't know whether this would be any better than the solution you've proposed though.

Anyway, once you're ready to push that fix to the remote branch, I'll try to help out with the testing. I'm feeling bad that I've been bringing nothing but problems to you, so I'd like to do what I can to reduce your debugging time at least.

**Comment by Aragas** [comment]
You've been a huge help actually. Pretty sure we would have a broken Fluent API for a much longer time if you weren't reporting issues!

The idea is that FluentGlobalSettings does not know which container class will actually use it, so it can't directly manipulate with FluentGlobalSettingsContainer.
The architecture is set so the setting classes don't interact with the containers directly. They are just models basically. Kinda.
Instead, we have some global storage (dictionary) that keeps all the fluent settings so that any container can pick them up.
Placing the container in the AppDomain is an interesting idea, but a more standard approach with dependency injection would be better

I will release 3.1.9 tomorrow

**Comment by mgemperl** [comment]
Ah, I get it. I suppose it would be best to not tie all fluid settings to a single container object. I hadn't realized the dictionary in AppDomain would be accessible globally to any number of containers. Thanks for the clarification, I feel like I'm learning more about C#, .NET, and Visual Studio just reading through this project. 

I'm not sure whether they came from you or Mippen, but I had never seen the null-coalescing operators ('??' and '??=') before. They're super convenient, and way better than all the ternary statements I've been using for my null-checking up until now.

And thanks for the Fluent API fix, too. I'm looking forward to getting my hands on it.

**Comment by mgemperl** [comment]
Awesome, I just tried out 3.1.9, and loading is now working with Fluent API. Thanks for all your hard work.

There's just one last Fluent API issue I think I've stumbled upon, but there is a workaround, so it shouldn't be too high priority. It's also possible I'm just not using it right.

I'm trying to create a toggle-able settings group with no nested groups, but neither of these methods below seem to work correctly. With both these methods, this test mod doesn't appear in the MCM mod options menu.

Defective Method # 1 
```
float _testFloat = 0;
bool _testToggle = true;
public void BuildSettings()
{
    var builder = new DefaultSettingsBuilder("Test_v1", "Test Mod")
        .SetFormat("json")
        .SetFolderName("Test Mod");

    builder.CreateGroup("Test Group", groupBuilder => groupBuilder
        .SetIsMainToggle(true)
        .AddBool("toggle_id", "Toggle Display Name",
            new ProxyRef<bool>(() => _testToggle, (value) => _testToggle = value),
            builder => builder.SetHintText("Toggle Hint")));

    builder.CreateGroup("Test Group", groupBuilder => groupBuilder
        .AddFloatingInteger("float_id", "Float Display Name", 0f, 20f,
            new ProxyRef<float>(() => _testFloat, (value) => _testFloat = value),
            builder => builder.SetHintText("Float Hint")));

    _settings = builder.BuildAsGlobal();
    _settings.Register();
}
```
Defective Method # 2
```
float _testFloat = 0;
bool _testToggle = true;
public void BuildSettings()
{
    var builder = new DefaultSettingsBuilder("Test_v1", "Test Mod")
        .SetFormat("json")
        .SetFolderName("Test Mod");

    builder.CreateGroup("Test Group", groupBuilder => groupBuilder
        .SetIsMainToggle(true)
        .AddBool("toggle_id", "Toggle Display Name",
            new ProxyRef<bool>(() => _testToggle, (value) => _testToggle = value),
            builder => builder.SetHintText("Toggle Hint"))
        .AddFloatingInteger("float_id", "Float Display Name", 0f, 20f,
            new ProxyRef<float>(() => _testFloat, (value) => _testFloat = value),
            builder => builder.SetHintText("Float Hint")));

    _settings = builder.BuildAsGlobal();
    _settings.Register();
}
```

However, it does work fine if I put the FloatingInteger setting into a nested group, like so:

Working Method
```
float _testFloat = 0;
bool _testToggle = true;
public void BuildSettings()
{
    var builder = new DefaultSettingsBuilder("Test_v1", "Test Mod")
        .SetFormat("json")
        .SetFolderName("Test Mod");

    builder.CreateGroup("Test Group Toggle", groupBuilder => groupBuilder
        .SetIsMainToggle(true)
        .AddBool("toggle_id", "Toggle Display Name",
            new ProxyRef<bool>(() => _testToggle, (value) => _testToggle = value),
            builder => builder.SetHintText("Toggle Hint")));

    // This is now a nested group
    builder.CreateGroup("Test Group Toggle/Settings", groupBuilder => groupBuilder
        .AddFloatingInteger("float_id", "Float Display Name", 0f, 20f,
            new ProxyRef<float>(() => _testFloat, (value) => _testFloat = value),
            builder => builder.SetHintText("Float Hint")));

    _settings = builder.BuildAsGlobal();
    _settings.Register();
}
```

Is there something else I'm supposed to be doing that's missing in the first two methods?

**Comment by Aragas** [comment]
Noted, will check this out today!

**Comment by Aragas** [comment]
Yep, it was implemented totally incorrect, mostly because of the Attribute API specifics.
The defective methods will work with 3.1.10
