### ISSUE TITLE
SubGroup not work.

### ISSUE THREAD

**Issue by jesseckwon** [Aragas/Bannerlord.MBOptionScreen#317]
I think SubGroup menu not working.
```
        [SettingPropertyInteger("Option 5", 0, 100, Order = 0, RequireRestart = false, HintText = "Option 1")]
        [SettingPropertyGroup("Level1/Level2/Level3/Level4/Level5")]
        public int Test_Option5 { get; set; } = 0;
```
(Sorry, my English not well.)
v5.0.4
![20221112163737_1](https://user-images.githubusercontent.com/34804033/201474795-f99a1b31-6138-42a0-bc4b-113c487021f3.jpg)

v5.1.1
![20221112151812_1](https://user-images.githubusercontent.com/34804033/201474808-89816606-e551-4935-98a3-6b3b7940e79a.jpg)

**Comment by Aragas** [comment]
Should be fixed in v5.2.0, please check!

**Comment by jesseckwon** [comment]
I am very sorry about this.
I think, it is my fault when I try to upgrade Mods from MCMv4 to MCMv5.
I create new project and test it again.
It works with all MCMv5 version.

v5.0.4
![20221113080119_1-v504](https://user-images.githubusercontent.com/34804033/201500780-7c87f5af-d741-440e-a3a9-f6472f3f09b6.jpg)

v5.1.1
![20221113075924_1-v511](https://user-images.githubusercontent.com/34804033/201500813-bf04862c-66d3-47a0-8c64-8bf6660b3138.jpg)


v5.2.0
![20221113080324_1-v520](https://user-images.githubusercontent.com/34804033/201500823-fbf18db7-0073-429d-810c-ead0448d0408.jpg)

**Comment by jesseckwon** [comment]
Now I found the problems.
It happen when no have SubGroup attributes.

When I comment code.
![code-mcmv5-problems](https://user-images.githubusercontent.com/34804033/201505391-a43539d9-f3f8-4189-b73b-e18c370eb86f.png)

Result:
![20221113110626_1](https://user-images.githubusercontent.com/34804033/201505413-0cfbd1f8-1544-43ff-9a46-b70fbbc935fb.jpg)

**Comment by Aragas** [comment]
Confirmed. WHile this seem like an user error, I should be able to fix it anyway

**Comment by jesseckwon** [comment]
Thank you.
It works on v5.3.0
![20221113194004_1](https://user-images.githubusercontent.com/34804033/201522231-3c945f3d-250c-4631-a9c7-c9a68085cb2e.jpg)
