### ISSUE TITLE
Any single mod with too many settings causes the entire "mod options" screen to be empty

### ISSUE THREAD

**Issue by ashakoor** [Aragas/Bannerlord.MBOptionScreen#33]
Settings details:
- Top-layer groups: 4
- Nested groups: 15
- Highest level of nesting: 2
- Number of settings, including main toggle groups: anything higher than 52 causes the issue.
- Using JSON storage format

If I remove any 4 settings from the mod, everything goes back to normal.
I've deleted the mod's config and that does not solve the issue.
Using non-integrated MCM 3.1.5 from NuGet.
Mod's source is available at ashakoor/UnlimitLord.

EDIT: Nevermind, I'm just an idiot. Forgot to edit a main toggle while copy-pasting. Turns out having a float as a main toggle breaks the whole mod options menu.

**Comment by Aragas** [comment]
Happens :grin:
MCM menu still should not break because of such simple errors. Was fixed in 3.1.9
