### ISSUE TITLE
Having issues with converting PerSave settings to PerCampaign

### ISSUE THREAD

**Issue by welles** [Aragas/Bannerlord.MBOptionScreen#346]
Hi, I tried converting my PerSave settings to PerCampaing, but I just can't get them to show up in game  when I do.
This is my current implementation of PerSaveSettings: [BannerlordCheatsPerSaveSettings.cs](https://github.com/welles/BannerlordCheats/blob/stable-develop/Settings/BannerlordCheatsPerSaveSettings.cs)
Is there something I must do in addition to deriving from `AttributePerCampaignSettings<T>`?
Cheers!

**Comment by Aragas** [comment]
Should be fixed with v5.5.3!

**Comment by welles** [comment]
Thanks! The cheats show up now, unfortunately they seem to not be initialized correctly when you start a new campaign, only after saving once and loading back in the game.

**Comment by Aragas** [comment]
Roger, will investigate

**Comment by Aragas** [comment]
What's the issue exactly with the initialization?
Also, I see there's some logic in the constructor. Because the Settings are used as a model by MCM, the class is instantiated multiple times, which might be a slowdown

**Comment by welles** [comment]
Sorry, my explanation was bad. When you start a new campaign and immediately go into the mod options after character creation, the per campaign settings do not show up. The JSON file for the per campaign settings is also not created. Only by saving, exiting to menu and loading the save again does the file get created and the per campaign settings show up in the mod options.

**Comment by Aragas** [comment]
Found the issue! I was getting the UniqueId of the Campaign on game start, not when it was loaded!

**Comment by Aragas** [comment]
Should be fixed with v5.5.4

**Comment by welles** [comment]
You're the best! I will check in the next days and close the issue.

**Comment by welles** [comment]
Works now, thanks!
