### ISSUE TITLE
Please target dotnet standard 2.0 instead of dotnet 4.x

### ISSUE THREAD

**Issue by Jarlotee** [Aragas/Bannerlord.MBOptionScreen#390]
It will make your library easier to use cross platform!

**Comment by Aragas** [comment]
Until the Game Pass PC version there was no need for that, since the only supported runtime was .NET Framework. The soon releasing version switched to .NET Standard 2.0! Will be available soon!

**Comment by Jarlotee** [comment]
@Aragas it looks like it has not been updated on nuget yet.

![image](https://user-images.githubusercontent.com/9733444/225497454-2795ed9c-3bde-4e47-96e5-1f4fdaf0009d.png)
