### ISSUE TITLE
Crash clicking Mod Options without Modlib installed

### ISSUE THREAD

**Issue by PoPoWanObi** [Aragas/Bannerlord.MBOptionScreen#4]
^Title.

Bugs are fun. xD

**Comment by Aragas** [comment]
Well, hm, it is expected. For compatibility, I call ModLibs code via reflection so it would handle save/loading. There might be a way to create a workaround when ModLib is not installed

**Comment by Adonnay76** [comment]
Dang it... yes, can confirm.

**Comment by Aragas** [comment]
Should be fixed in 1.1.11

**Comment by Aragas** [comment]
Further testing needed. There might be a case where it still will crash, if Instance references SettingsDatabase.
Most likely, in this case it will be needed to add ModLib.dll with my SettingsDatabase stump as a second dll in the NuGet package

**Comment by Aragas** [comment]
Yea, there was a confirmation. Stump incoming

**Comment by Aragas** [comment]
Well, I tried my best. The ModLib.dll stub will be required now to be included in mods to ensure backwards-compatibility with it.
The issue should be fixed now

**Comment by Aragas** [comment]
Further investigation has shown that I still fixed it in a limited case.
The best solution for now is to require ModLib if a ModLib setting screen is loaded.

I mean, the screens won't work without ModLib anyway and I'm don't remember advertising MBOptionScreen as a drop-in replacement. True, it can show ModLib setting screens, but still it can replicate ModLib in only a limited way.
The game does not allow more advanced tricks to make it a full replacement

**Comment by PoPoWanObi** [comment]
Fair enough. Thanks for your work yet again.

**Comment by Aragas** [comment]
I'll make some reverting changes like remove ModLib.dll from the NuGet package
