### ISSUE TITLE
NVIDIA sharpening causes visual glitch in manual number entry menu

### ISSUE THREAD

**Issue by ashakoor** [Aragas/Bannerlord.MBOptionScreen#44]
Example:
![sharpened](https://user-images.githubusercontent.com/60638768/85088253-ac83d180-b1ad-11ea-8097-5fc98ccd76d2.png)

Bannerlord e1.4.2, MCM 3.1.9, happens when using standard option screen as well.  
Some context, to my knowledge this visual glitch happens when sharpening hardware accelerated 2D applications, such as Electron apps.
IIRC this wasn't an issue in 3.1.6

**Comment by Aragas** [comment]
An interesting issue. I would've said that this is out of the scope of MCM, but I'm not totally sure.
There was a change between 3.1.6 and 3.1.9, but it was an internal one
Basically, the game uses a loading screen by default when changing screens, a popup meets the condition
This caused infinite loading loops in the standard option screen, so the loading screen was disabled.

I assume if you switch right now to 3.1.6 the visual glitches won't appear?
Maybe you changed some graphics related configs between the versions?

**Comment by ashakoor** [comment]
Yeah it must've been an NVIDIA-side thing, I updated drivers just before this started happening as well and going back to MCM v3.1.6 doesn't fix it.
