### ISSUE TITLE
New game hangs forever when click on [Cancel]

### ISSUE THREAD

**Issue by blackflag0623** [Aragas/Bannerlord.MBOptionScreen#442]
hi Aragas, thank you for the great menu framework provided!

I recently try to onboard to MCM5 and choose the `Fluent Builder` as I really want to benefit from the runtime setting creation.

I implement my setting following the example: https://github.com/jzebedee/ButterEquipped/blob/94e7de3a2000a6c611a8a84d43da01685f226abd/src/ButterEquipped/Settings/EquipSettings.cs

However, for a new game, when I first enter the Mod Configure panel and select my mod setting:
1. It will by default showing the [custom] preset as the selected preset, rather than [default] preset (I see for all other Mods, they are all by default with their [default] preset selected.
2. In this case, when I click the [Cancel] button of the Mod Configure panel, the game will stuck here forever.

<img width="960" alt="MCM new game hangs" src="https://github.com/Aragas/Bannerlord.MBOptionScreen/assets/50523939/21b19de6-3749-4410-8518-4937b2aeefdb">

My game version: `1.2.8`
ButterLib version: `2.9.8`
MCM version: `5.10.1`

Would you mind help check whether this is a common issue?

**Comment by Aragas** [comment]
Hey! I'm struggling a bit with GitHub notifications, sorry for not replying earlier! I'll try to take a look at it this week!

**Comment by blackflag0623** [comment]
Close the issue as it was caused by the bound variables not initialized.

Example code that would re-produce this issue:
``` CSHARP
[SettingPropertyFloatingInteger("哨骑 - 连胜行军速度加成", minValue: 0.001f, maxValue: 1f, Order = 3, RequireRestart = false, HintText = "哨骑战斗每一次连胜后，给与己方部队行军速度的加成。")]
[SettingPropertyGroup("哨骑")]
public float Sentry_WinningStreakPartySpeedBonus
{
    get => MBCampaign.Current.JunSiMa().Sentry_WinningStreakPartySpeedBonus;
    set => MBCampaign.Current.JunSiMa().Sentry_WinningStreakPartySpeedBonus = value;
}
```

For above example code, the MCM pane will hang forever when clicking on [Cancel] button --- if the `Sentry_WinningStreakPartySpeedBonus` is not set with init value.

I would like to conclude this issue to be more modder-usage side issue, thus I will close this issue.
