### ISSUE TITLE
Settings not displayed - 1.1.14

### ISSUE THREAD

**Issue by brandonm4** [Aragas/Bannerlord.MBOptionScreen#5]
@Aragas#7671 finally! ok - so there's no more crashing - it basically is doing this now:
1> Checks to see if ModLib or MBOptionScreen module is running
2> If so, checks to see if modlib.dll has been loaded into the current AppDomain
3> If not, it checks to see which one to use - if only MBOptionScreen is found it loads modlib.dll from your module folder.  
4> Then it loads my modlibsettings dll up via reflection and gets the settings from it.
5> It then sets the primary settings class to whatever settings system it found gave it.

Issue: It still doesn't show TournamentXPanded in the ModOptions list unless another modlib mod has already loaded.
I can confirm that Bannerlord does not load every dll in the bin folder by default.  Your modlib is not loaded until I do it manually, unless a different mod that directly references modlib is loaded first.
This may also be way TournamentXP doesn't show in the list, unless a different modlib mod is loaded first - you can't scan my assembly for modlib classes, they don't exist.  My suggestion would be when I call the normal SettingsDatabase.Register you add my settings to the list.  If already are, then I'm unsure now what the issue is.  My calls to your ModLib are returning a valid settings class.

(I did learn a ton about reflection today so it's been a good exercise so far)

Edit: Unless the modlib options aren't supposed to load if ModLib proper doesn't exist?  When I load the primary ModLib mod, and yours, everything is working I think.
I thought/think you were saying that even without the main ModLib module, modlib mods would still have an option screen.

**Comment by Aragas** [comment]
Yea, this is a game limitation that we cannot mitigate for every case. Mod orders will be important and other stuff.

It seems that if some mod relies on ModLib - it's a hard dependency that cannot be removed. There always should be loaded a ModLib module for it to work.
There isn't a good way to force load ModLib.dll into the game. The first code that gets to be executed by a submodule is in a too late stage. Even module initializers are worthless.

So yea, if you wanna some ModLib mod to work, load ModLib submodule first or get a crash

**Comment by brandonm4** [comment]
While working with you earlier I was able to get 1.1.14 to load and with ModLib running I was able to make settings changes and have them take effect.  However, I've now had an in the wild report of 1.1.14 fixing the problem with other mods that were causing issues with ModLib mods yesterday.  So I think the primary incompatibility issue is resolved.
