### ISSUE TITLE
Game becomes unpaused when entering options screen

### ISSUE THREAD

**Issue by welles** [Aragas/Bannerlord.MBOptionScreen#62]
Hi there,
I noticed that when entering the options screen via the escape menu, the game becomes unpaused in the background.
This is problematic for my mod because it is common for users to change its settings during combat encounters.
Could you make it so the game stays paused when the options screen is open?
Thanks and keep up the great work!

**Comment by Aragas** [comment]
Can't believe I didn't notice this issue until now. I'm sorry, GitHub has a shitty notification system.
Found the issue already, will be fixed in the next release!

**Comment by Aragas** [comment]
You can include this file in your module /bin folder. MCM should pick up this patch and fix you issue without the need to wait for the next version!
[MCMv3.Custom.Patch.InGamePause.v3.1.9.zip](https://github.com/Aragas/Bannerlord.MBOptionScreen/files/4978307/MCMv3.Custom.Patch.InGamePause.v3.1.9.zip)
