### ISSUE TITLE
Does MBOption Screen Support Localization?

### ISSUE THREAD

**Issue by SaulHE** [Aragas/Bannerlord.MBOptionScreen#8]
Hi Aragas:

Nice work here,

I read the Wiki. It says that Localization is supported in MBOptionScreen.

I am thinking of migrating to MBOptionScreen. 

How to localize the setting text with you lib? 
Maybe you could provide us with some examples, please?

Thanks

**Comment by Aragas** [comment]
Hi!
It's supported since 1.1.14 for both ``DisplayName`` and ``HintText`` properties in ``SettingPropertyAttribute``.
It's using the TextObject system from the game, so the format should be like this
```csharp
[SettingProperty("{=GqdfFr5F}Apply Relationship Rules to NPC", "{=HghfFr3F}Yourhint")]
```

**Comment by SaulHE** [comment]
So nice of you for explaining everything so clearly.

I will migrate to MBOptionScreen today.

Thank you for your work here. 

And I think MBOptionScreen is a much much better solution in every way, engineering, user-friendly, compatibility and everything.

**Comment by SaulHE** [comment]
I fucking love your lib.

PERIOD.

**Comment by Aragas** [comment]
Thanks!

**Comment by mgemperl** [comment]
Is there a good guide somewhere for hooking into Bannerlord's Localization system? I've been struggling a lot with it...
