### ISSUE TITLE
Color Picker?

### ISSUE THREAD

**Issue by 3ger** [Aragas/Bannerlord.MBOptionScreen#85]
First off, great job with this!

And now to my question, are there any plans to implement color pickers, so we are able to pick colors in the settings? Or is there such a feature already and I'm just missing it?

Thanks in advance!

**Comment by Aragas** [comment]
As I understand, the game does not have this functionality. It will require implementing a custom widget!
While this is am interesting feature, I'm not sure I'll have the time to implement such a widget. I'll be happy to collaborate with anyone who'll have the time and resource to create one tho!

**Comment by 3ger** [comment]
I'll look into it and see if I can come up with something.
Thanks for the fast reply :)

**Comment by 3ger** [comment]
I will close this, as I will not be able to invest the time needed for now.
