### ISSUE TITLE
Installing from NuGet, v2 api SettingPropertyBoolAttribute is internal and could not be accessed from CustomSetting class

### ISSUE THREAD

**Issue by SaulHE** [Aragas/Bannerlord.MBOptionScreen#9]
When I am trying to set up a configuration like in the wiki.

`[SettingPropertyBool(displayName: "Setting Name", order: 0, requireRestart: false, hintText: "Setting explanation.")]`

It got a popup saying that SettingPropertyBoolAttribute is an internal class.

`Cannot access the internal class here.`

I am using MBOptionScreen 1.1.15 installed from NuGet.

I use my JetBrain Rider to decompile `SettingPropertyBoolAttribute `. It says

```
namespace MBOptionScreen.Attributes
{
  [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
  internal class SettingPropertyBoolAttribute : BaseSettingPropertyAttribute
  {
    public SettingPropertyBoolAttribute(
      string displayName,
      int order = -1,
      bool requireRestart = true,
      string hintText = "")
      : base(displayName, order, requireRestart, hintText)
    {
    }
  }
}
```
Actually an internal class from my end

**Comment by Aragas** [comment]
Well, the v2 API was still a prototype for 1.1.15 and was not ready to be used!
I just included it to the actual sources for a preview, it will be available when MBOptionScreen v2 will be released!

**Comment by SaulHE** [comment]
Aight, Thanks.

I already use MBOptionScreen for my mod `Grow Up And Work` and release the new version using MBOptionScreen.

https://www.nexusmods.com/mountandblade2bannerlord/mods/544?tab=description

I would like to add my Mod in the wiki page "Mods using this library" of MBOptionScreen.

I would like to ask for your approval.

**Comment by Aragas** [comment]
Sorry for the late answer!
Sure, everyone can add their mods there, and you actually added it already!
