### ISSUE TITLE
Per Character Settings in v4

### ISSUE THREAD

**Issue by welles** [Aragas/Bannerlord.MBOptionScreen#93]
Hi, I was playing around with my mod settings and testing if I could convert them from global settings to per character settings.
However it seems like AttributePerCharacterSettings is not implemented in v4.
Is this not recommended? Is there a replacement or will this be supported in the future? Thanks!

**Comment by Aragas** [comment]
We replaced PerCharacter with PerSave, as there where identification issues. The new game API introduced some potential fixes, but I'm not sure it works as expected!

**Comment by welles** [comment]
Thanks for the info! I have tested it a bit and everything seems to work as ecpected. I saved and loaded multiple times after adding/removing settings and launching the save with and without my mod. No crashes or other problems so far.

**Comment by welles** [comment]
Well I may have spoken too soon. It seems like on further testing the settings are not saved or loaded correctly between game restarts. Every time I load a savegame all settings are reset...

**Comment by Aragas** [comment]
I'll check out the issue!

**Comment by Aragas** [comment]
Should be fixed with v4.3.6, please confirm!
Also, if you need to access some setting when the game is still loading, don't forget that they'll be available after the Behaviour's SyncData() was called!

**Comment by welles** [comment]
Thanks, the per save settings work now! Could you tell me why the "Mod Options" menu entry in the escape menu is gone? I worry that users may have a hard time finding the mod options if they're "buried" in the game settings.

**Comment by Aragas** [comment]
Yo! Sorry for the delay!
The reason for this is the e1.5.9 changes. This is a fallback behaviour for now!
I could make the entry in the Main Menu visible by default for now

**Comment by welles** [comment]
Oh ok, that's fine then. I thought it had something to do with my changing the settings type. XD This issue can be closed.
