### ISSUE TITLE
Mod does not show up in list after starting new campaign

### ISSUE THREAD

**Issue by welles** [Aragas/Bannerlord.MBOptionScreen#97]
Hi, as you may know I've converted BannerlordCheats to use PerSaveSettings.
Everything works great except that when starting a new campaign the mod does not show up in the MCM list until after saving, exiting to menu and loading the save again. Could you take a look at that?
Cheers

**Comment by Aragas** [comment]
Yo!
Sure, I'll check this out!

**Comment by Aragas** [comment]
0bf7ecee896d4d0115b65c39fb1334a16a20f54d should fix the issue, I'll release it soon!

**Comment by welles** [comment]
It works. Thanks for the quick fix!
